### PR TITLE
Import export transactions

### PR DESCRIPTION
**Pull request by 0xjimmy**

### CODE REVIEW

**Review by KillariDev — APPROVED** [review]
I guess this is just importing transactions?

**Comment by 0xjimmy** [comment]
image
Added modal to import JSON

**Comment by 0xjimmy** [comment]
Here is some valid demo transactions for importing
```json
[
  {
    "from": "0xb3cd36cfaa07652dbfecca76f438ff8998a4f539",
    "to": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
    "value": "0x16345785d8a0000",
    "input": "0xd0e30db0",
    "chainId": "0x1",
    "gasLimit": "0x15f90"
  },
  {
    "from": "0xb3cd36cfaa07652dbfecca76f438ff8998a4f539",
    "to": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
    "value": "0x0",
    "input": "0x2e1a7d4d000000000000000000000000000000000000000000000000016345785d8a0000",
    "chainId": "0x1",
    "gasLimit": "0x15f90"
  }
]
```

**Comment by MicahZoltu** [comment]
If we already have the private key, should we allow export with signatures?  That way if they want to submit via some other mechanism they can, and if they import later they don't have to add their key again.

**Pull request merged**
